# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import server

ui = None


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 748)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 761, 271))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.script_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.script_label.setObjectName("script_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.script_label)
        self.scriptLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.scriptLineEdit.sizePolicy().hasHeightForWidth()
        )
        self.scriptLineEdit.setSizePolicy(sizePolicy)
        self.scriptLineEdit.setMinimumSize(QtCore.QSize(600, 0))
        self.scriptLineEdit.setObjectName("scriptLineEdit")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.scriptLineEdit
        )
        self.scriptButton = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scriptButton.sizePolicy().hasHeightForWidth())
        self.scriptButton.setSizePolicy(sizePolicy)
        self.scriptButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scriptButton.setObjectName("scriptButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.scriptButton)
        self.prog_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.prog_label.setObjectName("prog_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.prog_label)
        self.progLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progLineEdit.sizePolicy().hasHeightForWidth())
        self.progLineEdit.setSizePolicy(sizePolicy)
        self.progLineEdit.setMinimumSize(QtCore.QSize(600, 0))
        self.progLineEdit.setObjectName("progLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.progLineEdit)
        self.progButton = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progButton.sizePolicy().hasHeightForWidth())
        self.progButton.setSizePolicy(sizePolicy)
        self.progButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.progButton.setObjectName("progButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.progButton)
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLineEdit.sizePolicy().hasHeightForWidth())
        self.nameLineEdit.setSizePolicy(sizePolicy)
        self.nameLineEdit.setMinimumSize(QtCore.QSize(600, 0))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.nameLineEdit)
        self.addButton = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.addButton.setObjectName("addButton")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.addButton)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 270, 761, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.startServerButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.startServerButton.setObjectName("startServerButton")
        self.gridLayout.addWidget(self.startServerButton, 4, 0, 1, 1)
        self.clientsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(False)
        self.clientsLabel.setFont(font)
        self.clientsLabel.setObjectName("clientsLabel")
        self.gridLayout.addWidget(self.clientsLabel, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Add Programs"))
        self.script_label.setText(_translate("MainWindow", "Select Script "))
        self.scriptButton.setText(_translate("MainWindow", "Select File"))
        self.prog_label.setText(_translate("MainWindow", "Select Main Program"))
        self.progButton.setText(_translate("MainWindow", "Select File"))
        self.nameLabel.setText(_translate("MainWindow", "Enter Program name"))
        self.addButton.setText(_translate("MainWindow", "Add program"))
        self.startServerButton.setText(_translate("MainWindow", "Start Server"))
        self.clientsLabel.setText(_translate("MainWindow", "Clients"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Device"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Key"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))

        self.scriptButton.clicked.connect(lambda b: self.clicked(b, 1))
        self.progButton.clicked.connect(lambda b: self.clicked(b, 2))
        self.addButton.clicked.connect(self.addProgram)
        self.startServerButton.clicked.connect(self.startServer)

    def clicked(self, b, button):
        options = QtWidgets.QFileDialog.Options()
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(
            self.scriptButton,
            "QtWidgets.QFileDialog.getOpenFileName()",
            "",
            "All Files (*);;Python Files (*.py)",
            options=options,
        )
        if button == 1:
            textBox = self.scriptLineEdit
        elif button == 2:
            textBox = self.progLineEdit

        if fileName:
            print(fileName)
            textBox.setText(fileName)

    def addProgram(self):
        program_file_path = self.progLineEdit.text()
        script_file_path = self.scriptLineEdit.text()
        program_name = self.nameLineEdit.text()

        print(program_file_path, script_file_path, program_name)

        server.add_program(program_name, script_file_path, program_file_path)

    def startServer(self):
        server.start(clientStatus)

    def clientStatusUpdate(self):
        tableWidget = self.tableWidget
        currentRowCount = tableWidget.rowCount()
        tableWidget.insertRow(currentRowCount)
        tableWidget.setItem(currentRowCount, 0, QtWidgets.QTableWidgetItem("text1"))
        tableWidget.setItem(currentRowCount, 1, QtWidgets.QTableWidgetItem("text2"))
        tableWidget.setItem(currentRowCount, 2, QtWidgets.QTableWidgetItem("text3"))
        pass


def clientStatus(name_map, authenticated_keys, connected_clients):
    client_ip = [str(i) for i in name_map]
    client_names = [name_map[i] for i in name_map]
    keys = [str(authenticated_keys[i]) for i in name_map]
    status = [
        "Connected" if i in connected_clients else "Disconnected" for i in name_map
    ]

    ui.clientStatusUpdate()
    print("her123e")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
